micronaut:
  application:
    name: casaDoCodigo
datasources:
  default:
    url: ${ DB_URL:`jdbc:postgresql://localhost:5432/db_casadocodigo` }
    driverClassName: org.postgresql.Driver
    username: ${ DB_USER:postgres }
    password: ${ DB_PASSWORD:password }
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: create-drop
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

